### ISSUE TITLE
Upgrade bcrypt version for compatibility

### ISSUE THREAD

**Issue by brylie** [apinf/restivus-swagger#11]
The bcrypt version in this package is lagging behind. It has caused compatibility issues, and outright errors when building.

# Task
Determine how to upgrade bcrypt in this project. Upgrade the bcrypt version here, or open an upstream PR.

# Original report
@radik originally reported the following.

@brylie I could not use latest version of restivus-swagger because of npm-bcrypt version:
```bash
➜  app meteor add apinf:restivus-swagger@0.3.0
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint npm-bcrypt@=0.8.5 is not satisfied by npm-bcrypt 0.9.2.
Constraints on package "npm-bcrypt":
* npm-bcrypt@0.9.2 <- top level
* npm-bcrypt@=0.8.5 <- apinf:restivus-swagger 0.3.1
* npm-bcrypt@0.9.2 <- accounts-password 1.3.4 <- nimble:restivus 0.8.7 <- apinf:restivus-swagger 0.3.1
```
Here I'm trying to add apinf:restivus-swagger@0.3.0 to newly created meteor application.

Could you help me with this?

**Comment by jykae** [comment]
Check out https://github.com/meteor-rest/restivus-swagger

**Comment by radik** [comment]
@brylie Steps to reproduce:
```
meteor create myapp
cd myapp
meteor add apinf:restivus-swagger@0.3.0
```

Meteor version: Meteor 1.4.3.1

**Comment by brylie** [comment]
Cool, thanks for the steps to reproduce. 

It seems like we can just unpin the dependency versions, and hopefully things will work correctly. It is unclear why the dependencies where pinned in the first place, and it is worth acknowledging the 'Meteor REST' organization seem to be willing to maintain this project in their own namespace.

cc: @bajiat

**Comment by radik** [comment]
@brylie Here is your comments about bcrypt:
https://github.com/apinf/restivus-swagger/issues/7#issuecomment-274321112
https://github.com/apinf/restivus-swagger/issues/7#issuecomment-274738931
and seems it was initial place, when bcrypt version is pinned.

Regarding to 'Meteor REST' organization package: `mrest:restivus-swagger` package has `mrest:restivus` as dependency, but I'm using `nimble:restivus`. 
I'm a bit confused. Who is maintainer for each of this packages?

As I understood, @kahmali is maintainer of `nimble:restivus` and @alfredjkwak initially developed `apinf:restivus-swagger`.

@alfredjkwak Could you clarify the situation? What is the difference between `nimble:restivus` and 'mrest:restivus'? Heads of this repositories are diverged now.

**Comment by jykae** [comment]
@radik Some of those Jan 24 PR merges, https://github.com/kahmali/meteor-restivus/commits/devel introduced bug https://github.com/kahmali/meteor-restivus/issues/259 that people seem to have solved by downgrading Restivus. 
So simply put, difference is that mrest:restivus misses those latest merged PRs that nimble:restivus has.

There is also discussion about time constraints of @kahmali https://github.com/kahmali/meteor-restivus/issues/233 So I thought to make initiative to build "Meteor REST community" as had idea to build also other package related to Restivus to support "design-first" way of API development in addition to "code-first" that restivus-swagger supports, check out https://swaggerhub.com/blog/api-design/design-first-or-code-first-api-development/

Thought community organization would be good place to host closely related packages to give developers a better user experience, and it would allow teams, group of maintainers, to join & share workload.

When it comes to Restivus, best place currently to discuss about that would though be https://github.com/kahmali/meteor-restivus/issues/233 
Haven't yet got answer from @kahmali if there's interest to transfer Restivus under organization. I have though invited & added him as admin to "Meteor REST" fork of Restivus. I am not interested to compete in any way with the fork, just want good experience for restivus-swagger package users.

I think I put gitter chat for Meteor REST for further discussion, it would be better place to have interactive discussion than this.

**Comment by jykae** [comment]
Meteor REST lobby: https://gitter.im/meteor-rest
Restivus Swagger room: https://gitter.im/meteor-rest/restivus-swagger

**Comment by brylie** [comment]
Thanks @dcantatore!

**Comment by brylie** [comment]
@dcantatore I would like to add you to our Atmosphere organization, so you can publish these package updates. What is your Atmosphere username?

**Comment by mauriciovieira** [comment]
@brylie please add myself too https://atmospherejs.com/mauriciovieira/

**Comment by brylie** [comment]
@mauriciovieira feito.

![screenshot_20170511_095752](https://cloud.githubusercontent.com/assets/17307/25936415/4e7df1c0-3630-11e7-8ccf-59185ba50b42.png)

**Comment by dcantatore** [comment]
@brylie  - On atmosphere I'm: dcantato

I should really stick to one or the other username some day.

**Comment by brylie** [comment]
@dcantatore I added you. 

As you can see, we have several collaborators. As a guideline moving forward, please have any PR reviewed by a collaborator before merging. This is a basic idea of peer review, so is not specific to your work.

**Comment by dcantatore** [comment]
@brylie Thanks for the heads up, I'll be sure to put things into review in the future.
