### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jykae** [apinf/restivus-swagger#14]
"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."

Reference: https://help.github.com/articles/licensing-a-repository/

**Comment by ccsr** [comment]
@jykae What exactly is your point here? What are you trying to suggest?

**Comment by jykae** [comment]
I propose MIT license so that everyone can use this kind of general use package. Fixed also on Sunday meteor-rest community version of restivus-swagger to have license. Looks like there are already over 200 installations using apinf:restivus-swagger based on Atmosphere installations number, basically breaking copyrights as long as package doesnt have license.

**Comment by dcantatore** [comment]
@ccsr 
I think he is trying to imply that without a license on the package it makes the users potentially in violation of copyright.  Are you the one that can push the latest updates to atmosphere? 

@jykae 
MIT is good and standard

**Comment by dcantatore** [comment]
Added:
https://github.com/apinf/restivus-swagger/blob/master/LICENSE

**Comment by jykae** [comment]
@ccsr @dcantatore In MIT licensing you are not allowed to change the copyright holder name. I did not have agreement to explicitly move my copyrights to Apinf Oy. I suppose in Finnish copyright law that is needed in addition to work contract? Or correct me If I am wrong.
Could you fix the copyright owner like this https://github.com/meteor-rest/restivus-swagger/blob/master/LICENSE ?

**Comment by jykae** [comment]
Finnish copyright law, http://www.finlex.fi/fi/laki/ajantasa/1961/19610404
In english, http://www.finlex.fi/en/laki/kaannokset/1961/en19610404
