### ISSUE TITLE
Publish 0.4.0 updates to Atmosphere

### ISSUE THREAD

**Issue by brylie** [apinf/restivus-swagger#15]
After recent improvements, we can publish a new version to Atmosphere. Determine version number and publish the new version.

**Comment by dcantatore** [comment]
I think 0.4.0 is good to go based on your PR:
https://github.com/apinf/restivus-swagger/pull/16

In the readme future it would be nice to have some jump to anchor links in the future with sections about features and subsections for the features. Example of the jump to:
https://github.com/kadirahq/flow-router

**Comment by brylie** [comment]
> In the readme future it would be nice to have some jump to anchor links in the future with sections about features and subsections for the features. Example of the jump to:
https://github.com/kadirahq/flow-router

Good idea. Since this issue is about the 0.4.0 release, would you consider adding that suggestion as a new issue? That way we can track it independently.

**Comment by brylie** [comment]
Closing this issue, since we have made the 0.4.0 release and published on Atmosphere.
