### ISSUE TITLE
Publish recent updates to Atmosphere

### ISSUE THREAD

**Issue by brylie** [apinf/restivus-swagger#7]
We accepted a recent pull request with changes to auth routes. Now we need to publish the updates to Atmosphere. Make sure to merge the second pull request with changes to README, and publish the new version to Atmosphere.

**Comment by brylie** [comment]
I was having troubles publishing to Atmoshpere, related to node building the plugin. There has been a long standing issue related to bcrypt, and I am not sure how to resolve it or where the issue resides. I will try the following solution on Monday:

http://stackoverflow.com/questions/29340510/bcrypt-is-breaking-my-meteor-application-how-do-i-fix-it#29347616

**Comment by jykae** [comment]
Released new versions with fix for bcrypt issue: https://atmospherejs.com/jykae/restivus-swagger … & https://atmospherejs.com/jykae/restivus

**Comment by jykae** [comment]
Released just 2 packages that fix issue with bcrypt https://atmospherejs.com/ajkwak

**Comment by brylie** [comment]
Thanks, @alfredjkwak. This morning, I was also able to resolve the problem with npm-bcrypt, by pinning it to a specific version. Any chance your fix will be contributed to the upstream project?

**Comment by jykae** [comment]
@brylie unfortunately not, but it's free to use
